# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Data in Public Policy'
tagline:          'Data in Public Policy'
description:      'Data in Public Policy (DiPP) is a student organization at the <a href="http://harrisschool.uchicago.edu" target="_blank">Harris School</a> focused on the intersection of data and public policy.'
hahadescription:	'Hack Harris, an initiative of <a href="/">Data in Public Policy</a>, is a group of data-oriented policy students at the <a href="http://harrisschool.uchicago.edu" target="_blank">Harris School</a> interested in ways to use data analysis and computer programming for public policy.'
url:              http://uc-dipp.github.io
baseurl:          /
author:
  name:           'Data in Public Policy'
  url:            http://uc-dipp.github.io

paginate:         5  # 5 posts per page

# Custom vars
version:          0.1

github:
  repo:           https://github.com/uc-dipp/uc-dipp.github.io
