# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'DiPP'
tagline:          'Data in Public Policy'
description:      'A student organization at the Harris School focused on the intersection of data and public policy.'
url:              http://hyde.getpoole.com
baseurl:          /
author:
  name:           'Data in Public Policy'
  url:            http://uc-dipp.github.io

paginate:         5  # 5 posts per page

# Custom vars
version:          0.1

github:
  repo:           https://github.com/uc-dipp/uc-dipp.github.io
